#!/usr/bin/env python3
"""
Step 6: Master orchestrator for the open-gate structure preparation pipeline
(3KDH/PYL2 backbone template version).

Runs all stages in sequence, with optional SLURM submission for the
compute-intensive threading/relax step.

Stages:
  0. Setup environment (deps, dirs, download 3KDH + 3QN1)
  1. Align sequences (3KDH / 3QN1 / Boltz three-way alignment)
  2. Generate params (ligand .params file from Boltz)
  3. Thread & relax (ALL mutations onto 3KDH + two-stage FastRelax) — SLURM bottleneck
  4. Place ligand (pocket-CA superposition)
  5. QC checks (RMSD, clashes, mutations)

Usage:
    # Local run (single test structure)
    python run_pipeline.py \
        --project-dir ml_modelling/open_gate_3kdh \
        --csv ml_modelling/analysis/boltz_LCA/md_candidates_lca_top100.csv \
        --smiles "C[C@H](CCC(=O)O)[C@@H]1CC..." \
        --single pair_3098

    # SLURM batch (all 120 structures)
    python run_pipeline.py \
        --project-dir ml_modelling/open_gate_3kdh \
        --csv ml_modelling/analysis/boltz_LCA/md_candidates_lca_top100.csv \
        --smiles "C[C@H](CCC(=O)O)..." \
        --slurm --batch-size 5

Author: Claude Code (Whitehead Lab PYR1 Pipeline)
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd


def get_script_dir():
    """Get absolute path to the scripts/ directory."""
    return Path(__file__).resolve().parent


def run_stage(stage_num, stage_name, cmd, cwd=None, skip_if_exists=None):
    """Run a pipeline stage as a subprocess."""
    if skip_if_exists and Path(skip_if_exists).exists():
        print(f"\n[Stage {stage_num}] {stage_name}: output exists, skipping")
        return True

    print(f"\n{'='*60}")
    print(f"[Stage {stage_num}] {stage_name}")
    print(f"{'='*60}")
    print(f"  Command: {' '.join(str(c) for c in cmd)}")

    result = subprocess.run(cmd, cwd=cwd)

    if result.returncode != 0:
        print(f"  FAILED (exit code {result.returncode})")
        return False

    print(f"  OK")
    return True


def generate_slurm_script(
    project_dir, manifest_path, scripts_dir, alignment_path,
    n_tasks, batch_size=1, n_relax=5, coord_sdev_a=0.3, coord_sdev_b=0.5,
    boltz_dir=None, params_path=None
):
    """Generate SLURM array job script for threading + ligand placement + relax (Stage 3)."""
    import math
    n_array = math.ceil(n_tasks / batch_size)

    template_clean = project_dir / "inputs" / "3KDH_chainA_clean.pdb"
    output_dir = project_dir / "outputs" / "threaded_relaxed"

    # Ligand flags for thread_and_relax.py
    ligand_flags = ""
    if boltz_dir:
        ligand_flags += f" \\\n        --boltz-dir {boltz_dir}"
    if params_path and Path(params_path).exists():
        ligand_flags += f" \\\n        --params {params_path}"

    slurm_content = f"""#!/bin/bash
#SBATCH --job-name=open_gate_3kdh
#SBATCH --output={project_dir}/logs/open_gate_%A_%a.out
#SBATCH --error={project_dir}/logs/open_gate_%A_%a.err
#SBATCH --partition=amilan
#SBATCH --qos=normal
#SBATCH --account=ucb472_asc2
#SBATCH --time=03:00:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=1
#SBATCH --array=1-{n_array}

# Open-gate structure prep (3KDH backbone): thread + place ligand + two-stage FastRelax
# Generated by run_pipeline.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}
#
# Each array task processes {batch_size} structure(s).
# Total: {n_tasks} structures across {n_array} array tasks.
# Two-stage relax: Stage A (sdev={coord_sdev_a}), Stage B (sdev={coord_sdev_b})
# Ligand placed BEFORE relax so packer avoids pocket clashes.

# --- USER: Edit module loads for your cluster environment ---
# module load anaconda3
# conda activate pyrosetta_env
# ---

cd "$SLURM_SUBMIT_DIR" || exit 1

MANIFEST="{manifest_path}"
BATCH_SIZE={batch_size}

TOTAL_LINES=$(wc -l < "$MANIFEST")

START_ROW=$(( (SLURM_ARRAY_TASK_ID - 1) * BATCH_SIZE + 1 ))
END_ROW=$(( SLURM_ARRAY_TASK_ID * BATCH_SIZE ))
if [ "$END_ROW" -gt "$TOTAL_LINES" ]; then
    END_ROW="$TOTAL_LINES"
fi

echo "Task ${{SLURM_ARRAY_TASK_ID}}: rows ${{START_ROW}}-${{END_ROW}}"
FAILURES=0

for ROW_NUM in $(seq "$START_ROW" "$END_ROW"); do
    LINE=$(sed -n "${{ROW_NUM}}p" "$MANIFEST")
    if [ -z "$LINE" ]; then
        continue
    fi

    IFS=$'\\t' read -r PAIR_ID SIGNATURE <<< "$LINE"

    OUTPUT_PDB="{output_dir}/${{PAIR_ID}}_threaded_relaxed.pdb"
    if [ -f "$OUTPUT_PDB" ]; then
        echo "  ${{PAIR_ID}}: already exists, skipping"
        continue
    fi

    echo "  Processing ${{PAIR_ID}}..."
    python {scripts_dir}/thread_and_relax.py \\
        --template {template_clean} \\
        --alignment {alignment_path} \\
        --signature "$SIGNATURE" \\
        --pair-id "$PAIR_ID" \\
        --output-dir {output_dir} \\
        --n-relax {n_relax} \\
        --coord-sdev-a {coord_sdev_a} \\
        --coord-sdev-b {coord_sdev_b}{ligand_flags}

    RC=$?
    if [ "$RC" -ne 0 ]; then
        echo "  ${{PAIR_ID}}: FAILED (exit $RC)"
        FAILURES=$((FAILURES + 1))
    fi
done

echo "Task ${{SLURM_ARRAY_TASK_ID}}: done, failures=${{FAILURES}}"
exit $FAILURES
"""

    slurm_path = project_dir / "submit_thread_relax.sh"
    with open(slurm_path, "w") as f:
        f.write(slurm_content)

    print(f"  SLURM script written to {slurm_path}")
    print(f"  Array: 1-{n_array}, batch_size={batch_size}")
    print(f"  Submit with: sbatch {slurm_path}")

    return slurm_path


def generate_placement_slurm_script(
    project_dir, manifest_path, scripts_dir, alignment_path,
    n_tasks, batch_size=10, params_path=None, minimize=False
):
    """Generate SLURM script for ligand placement (Stage 4)."""
    import math
    n_array = math.ceil(n_tasks / batch_size)

    threaded_dir = project_dir / "outputs" / "threaded_relaxed"
    boltz_dir = project_dir / "inputs" / "boltz_predictions"
    output_dir = project_dir / "outputs" / "open_gate_structures"

    minimize_flag = "--minimize" if minimize and params_path else ""
    params_flag = f"--params {params_path}" if params_path else ""

    slurm_content = f"""#!/bin/bash
#SBATCH --job-name=place_lig_3kdh
#SBATCH --output={project_dir}/logs/place_lig_%A_%a.out
#SBATCH --error={project_dir}/logs/place_lig_%A_%a.err
#SBATCH --partition=amilan
#SBATCH --qos=normal
#SBATCH --account=ucb472_asc2
#SBATCH --time=00:30:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=1
#SBATCH --array=1-{n_array}

# Open-gate (3KDH): ligand placement via pocket-CA superposition
# Generated by run_pipeline.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}

cd "$SLURM_SUBMIT_DIR" || exit 1

MANIFEST="{manifest_path}"
BATCH_SIZE={batch_size}

TOTAL_LINES=$(wc -l < "$MANIFEST")

START_ROW=$(( (SLURM_ARRAY_TASK_ID - 1) * BATCH_SIZE + 1 ))
END_ROW=$(( SLURM_ARRAY_TASK_ID * BATCH_SIZE ))
if [ "$END_ROW" -gt "$TOTAL_LINES" ]; then
    END_ROW="$TOTAL_LINES"
fi

echo "Task ${{SLURM_ARRAY_TASK_ID}}: rows ${{START_ROW}}-${{END_ROW}}"

for ROW_NUM in $(seq "$START_ROW" "$END_ROW"); do
    PAIR_ID=$(sed -n "${{ROW_NUM}}p" "$MANIFEST" | cut -f1)
    if [ -z "$PAIR_ID" ]; then continue; fi

    THREADED="{threaded_dir}/${{PAIR_ID}}_threaded_relaxed.pdb"
    BOLTZ="{boltz_dir}/${{PAIR_ID}}.pdb"
    OUTPUT="{output_dir}/${{PAIR_ID}}_open_gate.pdb"

    if [ -f "$OUTPUT" ]; then
        echo "  ${{PAIR_ID}}: exists, skipping"
        continue
    fi

    if [ ! -f "$THREADED" ] || [ ! -f "$BOLTZ" ]; then
        echo "  ${{PAIR_ID}}: missing input, skipping"
        continue
    fi

    python {scripts_dir}/place_ligand.py \\
        --threaded-pdb "$THREADED" \\
        --boltz-pdb "$BOLTZ" \\
        --alignment {alignment_path} \\
        --output "$OUTPUT" \\
        {params_flag} {minimize_flag}
done
"""

    slurm_path = project_dir / "submit_place_ligand.sh"
    with open(slurm_path, "w") as f:
        f.write(slurm_content)

    return slurm_path


def main():
    parser = argparse.ArgumentParser(
        description="Master orchestrator for open-gate structure prep (3KDH backbone)"
    )
    parser.add_argument("--project-dir", required=True,
                        help="Root directory (e.g., ml_modelling/open_gate_3kdh)")
    parser.add_argument("--csv", required=True,
                        help="CSV with pair_id and variant_signature columns")
    parser.add_argument("--smiles", required=True,
                        help="SMILES string for the ligand")
    parser.add_argument("--ligand-name", default="LCA",
                        help="3-letter name for the ligand (default: LCA)")

    # Control
    parser.add_argument("--single",
                        help="Process only this pair_id (for testing)")
    parser.add_argument("--skip-to", type=int, default=0,
                        help="Skip to this stage number (0-5)")
    parser.add_argument("--stop-after", type=int, default=5,
                        help="Stop after this stage number (0-5)")

    # SLURM
    parser.add_argument("--slurm", action="store_true",
                        help="Generate SLURM submission scripts")
    parser.add_argument("--batch-size", type=int, default=1,
                        help="Structures per SLURM array task (default: 1)")

    # Relaxation
    parser.add_argument("--n-relax", type=int, default=5,
                        help="Number of FastRelax trajectories (default: 5)")
    parser.add_argument("--coord-sdev-a", type=float, default=0.3,
                        help="Stage A coordinate constraint sdev (default: 0.3 A)")
    parser.add_argument("--coord-sdev-b", type=float, default=0.5,
                        help="Stage B coordinate constraint sdev (default: 0.5 A)")

    # Ligand placement
    parser.add_argument("--minimize", action="store_true",
                        help="Run Rosetta minimization after ligand placement")

    # Boltz PDB location
    parser.add_argument("--boltz-dir",
                        help="Directory with Boltz PDBs (default: inputs/boltz_predictions/)")

    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()
    scripts_dir = get_script_dir()
    csv_path = Path(args.csv).resolve()

    inputs_dir = project_dir / "inputs"
    outputs_dir = project_dir / "outputs"
    params_dir = project_dir / "params"
    if args.boltz_dir:
        boltz_dir = Path(args.boltz_dir).resolve()
    else:
        boltz_dir = inputs_dir / "boltz_predictions"
    alignment_path = project_dir / "alignment_map.json"
    params_path = params_dir / f"{args.ligand_name}.params"

    print(f"Open-Gate PYR1 Structure Prep (3KDH/PYL2 backbone)")
    print(f"Project directory: {project_dir}")
    print(f"CSV: {csv_path}")
    print(f"SLURM mode: {args.slurm}")
    if args.single:
        print(f"Single mode: {args.single}")

    df = pd.read_csv(csv_path)
    if args.single:
        df = df[df["pair_id"] == args.single]
        if df.empty:
            print(f"ERROR: pair_id '{args.single}' not found in CSV")
            sys.exit(1)
    n_variants = len(df)
    print(f"Variants to process: {n_variants}")

    # ── Stage 0: Setup ──────────────────────────────────────────────
    if args.skip_to <= 0 and args.stop_after >= 0:
        cmd = [
            sys.executable, str(scripts_dir / "setup_environment.py"),
            "--project-dir", str(project_dir),
            "--skip-deps",
        ]
        if args.boltz_dir:
            cmd.extend(["--link-boltz-pdbs", str(boltz_dir)])
        if not run_stage(0, "Setup Environment", cmd):
            print("Stage 0 failed.")
            sys.exit(1)

    # Verify Boltz PDBs
    if not any(boltz_dir.glob("*.pdb")):
        print(f"ERROR: No Boltz PDBs found in {boltz_dir}")
        print("  Provide --boltz-dir pointing to your Boltz PDB directory.")
        sys.exit(1)
    print(f"Boltz PDB directory: {boltz_dir}")

    # ── Stage 1: Three-Way Alignment ───────────────────────────────
    if args.skip_to <= 1 and args.stop_after >= 1:
        ref_boltz = None
        for _, row in df.iterrows():
            bp = boltz_dir / f"{row['pair_id']}.pdb"
            if bp.exists():
                ref_boltz = bp
                break

        if ref_boltz is None:
            print("ERROR: No Boltz PDB found. Check --boltz-dir.")
            sys.exit(1)

        cmd = [
            sys.executable, str(scripts_dir / "align_sequences.py"),
            "--pdb-3kdh", str(inputs_dir / "3KDH.pdb"),
            "--pdb-3qn1", str(inputs_dir / "3QN1.pdb"),
            "--boltz-pdb", str(ref_boltz),
            "--output-json", str(alignment_path),
        ]
        if not run_stage(1, "Three-Way Alignment", cmd,
                        skip_if_exists=str(alignment_path)):
            print("Stage 1 failed.")
            sys.exit(1)

    # ── Stage 2: Generate Params ────────────────────────────────────
    if args.skip_to <= 2 and args.stop_after >= 2:
        ref_boltz = None
        for _, row in df.iterrows():
            bp = boltz_dir / f"{row['pair_id']}.pdb"
            if bp.exists():
                ref_boltz = bp
                break

        cmd = [
            sys.executable, str(scripts_dir / "generate_params.py"),
            "--boltz-pdb", str(ref_boltz),
            "--smiles", args.smiles,
            "--output-dir", str(params_dir),
            "--name", args.ligand_name,
            "--skip-validation",
        ]
        if not run_stage(2, "Generate Params", cmd,
                        skip_if_exists=str(params_path)):
            print("Stage 2 failed (non-critical).")

    # ── Stage 3: Thread, Place Ligand & Two-Stage Relax ─────────────
    if args.skip_to <= 3 and args.stop_after >= 3:
        if args.slurm:
            manifest_path = project_dir / "thread_manifest.tsv"
            with open(manifest_path, "w") as f:
                for _, row in df.iterrows():
                    f.write(f"{row['pair_id']}\t{row['variant_signature']}\n")
            print(f"  Manifest written: {manifest_path} ({n_variants} rows)")

            template_clean = inputs_dir / "3KDH_chainA_clean.pdb"
            if not template_clean.exists():
                print("  Preparing clean 3KDH template...")
                sys.path.insert(0, str(scripts_dir))
                from thread_and_relax import prepare_template
                prepare_template(str(inputs_dir / "3KDH.pdb"), "A", str(template_clean))

            slurm_path = generate_slurm_script(
                project_dir, manifest_path, scripts_dir, alignment_path,
                n_variants, args.batch_size, args.n_relax,
                args.coord_sdev_a, args.coord_sdev_b,
                boltz_dir=boltz_dir, params_path=params_path
            )
            print(f"\n  Submit Stage 3 with:")
            print(f"    sbatch {slurm_path}")
            print(f"  Then re-run with --skip-to 4 to continue.")
            if args.stop_after <= 3:
                return
        else:
            cmd = [
                sys.executable, str(scripts_dir / "thread_and_relax.py"),
                "--template", str(inputs_dir / "3KDH.pdb"),
                "--alignment", str(alignment_path),
                "--csv", str(csv_path),
                "--output-dir", str(outputs_dir / "threaded_relaxed"),
                "--n-relax", str(args.n_relax),
                "--coord-sdev-a", str(args.coord_sdev_a),
                "--coord-sdev-b", str(args.coord_sdev_b),
                "--boltz-dir", str(boltz_dir),
            ]
            if params_path.exists():
                cmd.extend(["--params", str(params_path)])
            if args.single:
                cmd.extend(["--single", args.single])

            if not run_stage(3, "Thread, Place Ligand & Two-Stage Relax", cmd):
                print("Stage 3 failed.")
                sys.exit(1)

    # ── Stage 4: Place Ligand (legacy / fallback) ────────────────────
    # NOTE: If Stage 3 was run with --boltz-dir and --params, the output PDBs
    # already contain the ligand (placed before relax). Stage 4 is only needed
    # if Stage 3 was run without ligand params (backward compatibility).
    if args.skip_to <= 4 and args.stop_after >= 4:
        if args.slurm and not args.single:
            manifest_path = project_dir / "placement_manifest.tsv"
            with open(manifest_path, "w") as f:
                for _, row in df.iterrows():
                    f.write(f"{row['pair_id']}\n")

            slurm_path = generate_placement_slurm_script(
                project_dir, manifest_path, scripts_dir, alignment_path,
                n_variants, batch_size=max(args.batch_size * 2, 10),
                params_path=params_path if params_path.exists() else None,
                minimize=args.minimize
            )
            print(f"\n  Submit Stage 4 with:")
            print(f"    sbatch {slurm_path}")
            print(f"  Then re-run with --skip-to 5 for QC.")
            if args.stop_after <= 4:
                return
        else:
            cmd = [
                sys.executable, str(scripts_dir / "place_ligand.py"),
                "--threaded-dir", str(outputs_dir / "threaded_relaxed"),
                "--boltz-dir", str(boltz_dir),
                "--alignment", str(alignment_path),
                "--csv", str(csv_path),
                "--output-dir", str(outputs_dir / "open_gate_structures"),
            ]
            if params_path.exists():
                cmd.extend(["--params", str(params_path)])
            if args.minimize:
                cmd.append("--minimize")
            if args.single:
                cmd.extend(["--single", args.single])

            if not run_stage(4, "Place Ligand", cmd):
                print("Stage 4 had errors.")

    # ── Stage 5: QC Checks ──────────────────────────────────────────
    if args.skip_to <= 5 and args.stop_after >= 5:
        qc_report = outputs_dir / "qc_report.csv"
        cmd = [
            sys.executable, str(scripts_dir / "check_structure.py"),
            "--input-dir", str(outputs_dir / "open_gate_structures"),
            "--template", str(inputs_dir / "3KDH.pdb"),
            "--boltz-dir", str(boltz_dir),
            "--alignment", str(alignment_path),
            "--csv", str(csv_path),
            "--output-csv", str(qc_report),
            "--pml-dir", str(outputs_dir / "open_gate_structures"),
        ]
        if args.single:
            cmd.extend(["--single", args.single])

        if not run_stage(5, "QC Checks", cmd):
            print("Stage 5 had errors.")

        if qc_report.exists():
            report = pd.read_csv(qc_report)
            print(f"\n{'='*60}")
            print("FINAL SUMMARY")
            print(f"{'='*60}")
            print(f"Total structures: {len(report)}")
            for status, count in report["status"].value_counts().items():
                print(f"  {status}: {count}")
            print(f"\nQC report: {qc_report}")
            print(f"Open-gate structures: {outputs_dir / 'open_gate_structures'}/")

    # Save pipeline state
    state = {
        "timestamp": datetime.now().isoformat(),
        "csv": str(csv_path),
        "n_variants": n_variants,
        "single": args.single,
        "slurm": args.slurm,
        "last_stage": min(args.stop_after, 5),
        "template": "3KDH",
        "coord_sdev_a": args.coord_sdev_a,
        "coord_sdev_b": args.coord_sdev_b,
    }
    state_path = project_dir / "pipeline_state.json"
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)

    print(f"\nPipeline state saved to {state_path}")


if __name__ == "__main__":
    main()
