#!/bin/bash
# ============================================================================
# Master workflow: Prepare & submit Boltz2 binary predictions for nitazene SSM
# ============================================================================
#
# Run this interactively on an Alpine login node (NOT as a SLURM job).
# It will:
#   1. Generate Boltz YAML inputs with MSA patching for nitazene & menitazene
#   2. Submit SLURM array jobs for each ligand
#
# Usage:
#   cd /projects/ryde3462/software/pyr1_pipeline
#   bash slurm/run_boltz_nitazene_binary.sh
#
# Prerequisites:
#   - boltz_env conda environment
#   - nitazene_boltz_binary.csv (generated by parse_nitazene_ssm.py)
#   - WT PYR1 MSA from previous run (reused from LCA predictions)
# ============================================================================

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────

PROJECT_ROOT="/projects/ryde3462/software/pyr1_pipeline"
SCRATCH="/scratch/alpine/ryde3462/boltz_nitazene"

# Input CSV (both ligands in one file, filtered by --ligand-filter)
INPUT_CSV="${PROJECT_ROOT}/ml_modelling/data/nitazene_boltz_binary.csv"

# WT PYR1 MSA (reuse from LCA predictions — protein-only, ligand-independent)
WT_MSA="/scratch/alpine/ryde3462/boltz_lca/wt_prediction/boltz_results_pyr1_wt_lca/msa/pyr1_wt_lca_unpaired_tmp_env/uniref.a3m"

# Boltz settings
DIFFUSION_SAMPLES=5   # binary mode
BATCH_SIZE=20

LIGANDS=("nitazene" "menitazene")

# ── Step 0: Activate environment ──────────────────────────────────────────
echo "============================================"
echo "Step 0: Activating environment"
echo "============================================"

module load anaconda
source activate boltz_env

# ── Step 1: Verify inputs ────────────────────────────────────────────────
echo ""
echo "============================================"
echo "Step 1: Verify inputs"
echo "============================================"

if [ ! -f "${INPUT_CSV}" ]; then
    echo "ERROR: Input CSV not found: ${INPUT_CSV}"
    echo "Generate it first: python ml_modelling/scripts/parse_nitazene_ssm.py"
    exit 1
fi
echo "Input CSV: ${INPUT_CSV} ($(wc -l < "${INPUT_CSV}") lines)"

if [ ! -f "${WT_MSA}" ]; then
    echo "ERROR: WT MSA not found at ${WT_MSA}"
    echo "Generate it first with: sbatch slurm/predict_wt_pyr1.sh"
    exit 1
fi
echo "WT MSA: ${WT_MSA} ($(wc -l < "${WT_MSA}") lines)"

mkdir -p "${SCRATCH}"

# ── Step 2+3: Generate YAMLs and submit jobs per ligand ───────────────────
echo ""
echo "============================================"
echo "Step 2: Generate Boltz YAML inputs + submit jobs"
echo "============================================"

SUBMIT_SCRIPT="${PROJECT_ROOT}/slurm/submit_boltz.sh"
SUBMITTED_JOBS=()

for LIG in "${LIGANDS[@]}"; do
    YAML_DIR="${SCRATCH}/inputs_${LIG}_binary"
    OUTPUT_DIR="${SCRATCH}/output_${LIG}_binary"

    echo ""
    echo "--- ${LIG^^} ---"
    python "${PROJECT_ROOT}/scripts/prepare_boltz_yamls.py" \
        "${INPUT_CSV}" \
        --out-dir "${YAML_DIR}" \
        --mode binary \
        --msa "${WT_MSA}" \
        --affinity \
        --ligand-filter "${LIG}"

    MANIFEST="${YAML_DIR}/manifest.txt"
    TOTAL=$(wc -l < "${MANIFEST}")

    if [ "${TOTAL}" -eq 0 ]; then
        echo "No predictions for ${LIG^^}, skipping"
        continue
    fi

    ARRAY_MAX=$(( (TOTAL + BATCH_SIZE - 1) / BATCH_SIZE - 1 ))
    echo "${LIG^^}: ${TOTAL} YAMLs -> array=0-${ARRAY_MAX} (batch=${BATCH_SIZE})"

    echo "Submitting ${LIG^^} (${TOTAL} predictions)..."
    JOB_ID=$(sbatch --array=0-${ARRAY_MAX} \
        --job-name=boltz_${LIG} \
        "${SUBMIT_SCRIPT}" \
        "${MANIFEST}" "${OUTPUT_DIR}" "${BATCH_SIZE}" "${DIFFUSION_SAMPLES}" \
        | awk '{print $NF}')
    echo "  ${LIG^^} job: ${JOB_ID}"
    SUBMITTED_JOBS+=("${LIG^^}:${JOB_ID}:${TOTAL}")
done

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "============================================"
echo "ALL DONE"
echo "============================================"
echo ""
echo "Jobs submitted:"
for entry in "${SUBMITTED_JOBS[@]}"; do
    IFS=':' read -r lig job total <<< "$entry"
    echo "  ${lig}: job ${job} (${total} predictions)"
done
echo ""
echo "Settings: diffusion_samples=${DIFFUSION_SAMPLES}, batch_size=${BATCH_SIZE}, affinity=yes"
echo ""
echo "Monitor: squeue -u \$USER"
echo ""
echo "After completion, aggregate results:"
echo ""

NIT_SMILES='CCN(CC)CCN1C2=C(C=C(C=C2)[N+](=O)[O-])N=C1CC3=CC=CC=C3'
MEN_SMILES='CCN(CC)CCN1C2=C(C=C(C=C2)[N+](=O)[O-])N=C1CC3=CC=C(C=C3)OC'

echo "  # Nitazene"
echo "  python ${PROJECT_ROOT}/scripts/analyze_boltz_output.py \\"
echo "      --binary-dir ${SCRATCH}/output_nitazene_binary \\"
echo "      --ref-pdb ${PROJECT_ROOT}/docking/ligand_alignment/files_for_PYR1_docking/3QN1_H2O.pdb \\"
echo "      --ligand-smiles '${NIT_SMILES}' \\"
echo "      --out ${SCRATCH}/boltz_nitazene_results.csv"
echo ""
echo "  # Menitazene"
echo "  python ${PROJECT_ROOT}/scripts/analyze_boltz_output.py \\"
echo "      --binary-dir ${SCRATCH}/output_menitazene_binary \\"
echo "      --ref-pdb ${PROJECT_ROOT}/docking/ligand_alignment/files_for_PYR1_docking/3QN1_H2O.pdb \\"
echo "      --ligand-smiles '${MEN_SMILES}' \\"
echo "      --out ${SCRATCH}/boltz_menitazene_results.csv"
echo ""
echo "Then merge with labels:"
echo "  (merge boltz_nitazene_results.csv with nitazene_ssm_labeled.csv on variant name)"
