#!/bin/bash
# ============================================================================
# One-off Boltz2 binary predictions for CDCA non-binder designs
# ============================================================================
#
# Run interactively on Alpine login node (NOT as a SLURM job).
#   1. Generates Boltz YAML inputs with MSA patching + affinity
#   2. Submits SLURM array job
#
# Usage:
#   cd /projects/ryde3462/software/pyr1_pipeline
#   bash slurm/run_boltz_cdca_nonbinders.sh
#
# Prerequisites:
#   - boltz_env conda environment
#   - WT PYR1 MSA from previous run (reused from LCA predictions)
# ============================================================================

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────

PROJECT_ROOT="/projects/ryde3462/software/pyr1_pipeline"
SCRATCH="/scratch/alpine/ryde3462/boltz_cdca_nonbinders"

# Input CSV (generated by prepare_cdca_nonbinder_boltz_csv.py)
INPUT_CSV="${PROJECT_ROOT}/ml_modelling/data/boltz_cdca_nonbinders_binary.csv"

# WT PYR1 MSA (reuse from LCA predictions — MSA is protein-only, ligand-independent)
WT_MSA="/scratch/alpine/ryde3462/boltz_lca/wt_prediction/boltz_results_pyr1_wt_lca/msa/pyr1_wt_lca_unpaired_tmp_env/uniref.a3m"

# Boltz settings
DIFFUSION_SAMPLES=5   # binary mode
BATCH_SIZE=20          # 24 variants -> 2 array tasks

YAML_DIR="${SCRATCH}/inputs_binary"
OUTPUT_DIR="${SCRATCH}/output_binary"

# CDCA SMILES (for post-analysis)
CDCA_SMILES='C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2[C@@H](C[C@H]4[C@@]3(CC[C@H](C4)O)C)O)C'

# ── Step 0: Activate environment ──────────────────────────────────────────
echo "============================================"
echo "Step 0: Activating environment"
echo "============================================"

module load anaconda
source activate boltz_env

# ── Step 1: Verify inputs ────────────────────────────────────────────────
echo ""
echo "============================================"
echo "Step 1: Verify inputs"
echo "============================================"

if [ ! -f "${INPUT_CSV}" ]; then
    echo "ERROR: Input CSV not found: ${INPUT_CSV}"
    echo "Run first: python scripts/prepare_cdca_nonbinder_boltz_csv.py"
    exit 1
fi
echo "Input CSV: ${INPUT_CSV} ($(tail -n +2 "${INPUT_CSV}" | wc -l) variants)"

if [ ! -f "${WT_MSA}" ]; then
    echo "ERROR: WT MSA not found at ${WT_MSA}"
    exit 1
fi
echo "WT MSA: ${WT_MSA}"

# ── Step 2: Generate Boltz YAML inputs with MSA patching ─────────────────
echo ""
echo "============================================"
echo "Step 2: Generate Boltz YAML inputs (binary, MSA-patched)"
echo "============================================"

python "${PROJECT_ROOT}/scripts/prepare_boltz_yamls.py" \
    "${INPUT_CSV}" \
    --out-dir "${YAML_DIR}" \
    --mode binary \
    --msa "${WT_MSA}" \
    --affinity

# ── Step 3: Submit SLURM array job ────────────────────────────────────────
echo ""
echo "============================================"
echo "Step 3: Submit SLURM job"
echo "============================================"

MANIFEST="${YAML_DIR}/manifest.txt"
TOTAL=$(wc -l < "${MANIFEST}")
ARRAY_MAX=$(( (TOTAL + BATCH_SIZE - 1) / BATCH_SIZE - 1 ))
echo "CDCA non-binders: ${TOTAL} YAMLs -> array=0-${ARRAY_MAX} (batch=${BATCH_SIZE})"

SUBMIT_SCRIPT="${PROJECT_ROOT}/slurm/submit_boltz.sh"

JOB_ID=$(sbatch --array=0-${ARRAY_MAX} \
    --job-name=boltz_cdca_nb \
    "${SUBMIT_SCRIPT}" \
    "${MANIFEST}" "${OUTPUT_DIR}" "${BATCH_SIZE}" "${DIFFUSION_SAMPLES}" \
    | awk '{print $NF}')
echo "Submitted job: ${JOB_ID}"

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "============================================"
echo "DONE"
echo "============================================"
echo ""
echo "Job: ${JOB_ID} (${TOTAL} predictions, batch_size=${BATCH_SIZE})"
echo "Settings: diffusion_samples=${DIFFUSION_SAMPLES}, affinity=yes, MSA-patched, no template"
echo ""
echo "Monitor: squeue -u \$USER"
echo ""
echo "After completion, aggregate results:"
echo ""
echo "  python ${PROJECT_ROOT}/scripts/analyze_boltz_output.py \\"
echo "      --binary-dir ${OUTPUT_DIR} \\"
echo "      --ref-pdb ${PROJECT_ROOT}/docking/ligand_alignment/files_for_PYR1_docking/3QN1_H2O.pdb \\"
echo "      --ligand-smiles '${CDCA_SMILES}' \\"
echo "      --out ${SCRATCH}/boltz_cdca_nonbinders_results.csv"
echo ""
