#!/bin/bash
# ============================================================================
# Master workflow: Prepare & submit ternary Boltz2 predictions with PAIRED MSAs
# for LCA, GLCA, and LCA-3-S training data (PYR1 + ligand + HAB1)
# ============================================================================
#
# Uses species-paired CSV MSAs from the WT ternary prediction (run with
# --use_msa_server) instead of unpaired .a3m files. Paired MSAs provide
# co-evolutionary signal for the PYR1-HAB1 interface, which should improve
# ternary_iptm (was 0.55 AUC with unpaired MSAs).
#
# CSV format: key,sequence
#   - Same key across PYR1/HAB1 CSVs = paired homologs (same organism)
#   - key=0 = query sequence (patched per variant for PYR1)
#   - key=-1 = unpaired homologs
#
# Run interactively on an Alpine login node (NOT as a SLURM job).
#
# Usage:
#   cd /projects/ryde3462/software/pyr1_pipeline
#   bash slurm/run_boltz_lca_ternary_paired.sh
#
# Prerequisites:
#   - boltz_env conda environment (with confidence patch applied)
#   - Paired CSV MSAs from WT ternary prediction
#   - Existing conjugate CSVs in $CONJUGATE_DIR
# ============================================================================

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────

PROJECT_ROOT="/projects/ryde3462/software/pyr1_pipeline"
SCRATCH="/scratch/alpine/ryde3462/boltz_lca"

# Paired CSV MSAs from WT ternary prediction (run with --use_msa_server)
PYR1_MSA="${SCRATCH}/wt_ternary/boltz_results_pyr1_wt_lca_hab1/msa/pyr1_wt_lca_hab1_0.csv"
HAB1_MSA="${SCRATCH}/wt_ternary/boltz_results_pyr1_wt_lca_hab1/msa/pyr1_wt_lca_hab1_2.csv"

# Reference PDB with conserved water
REF_PDB="${PROJECT_ROOT}/docking/ligand_alignment/files_for_PYR1_docking/3QN1_H2O.pdb"

# Conjugate CSV directory
CONJUGATE_DIR="${PROJECT_ROOT}/ml_modelling/data/boltz_lca_conjugates"

# Ternary YAML input directories (paired)
LCA_YAML_DIR="${SCRATCH}/inputs_lca_ternary_paired"
GLCA_YAML_DIR="${SCRATCH}/inputs_glca_ternary_paired"
LCA3S_YAML_DIR="${SCRATCH}/inputs_lca3s_ternary_paired"

# Ternary output directories (paired)
LCA_OUTPUT_DIR="${SCRATCH}/output_lca_ternary_paired"
GLCA_OUTPUT_DIR="${SCRATCH}/output_glca_ternary_paired"
LCA3S_OUTPUT_DIR="${SCRATCH}/output_lca3s_ternary_paired"

# Boltz settings
DIFFUSION_SAMPLES=5   # same as binary for quality
BATCH_SIZE=10          # ternary ~5 min each

# ── Step 0: Activate environment ──────────────────────────────────────────
echo "============================================"
echo "Step 0: Activating environment"
echo "============================================"

module load anaconda
source activate boltz_env

# ── Step 1: Verify paired CSV MSAs ───────────────────────────────────────
echo ""
echo "============================================"
echo "Step 1: Verify paired CSV MSAs"
echo "============================================"

if [ ! -f "${PYR1_MSA}" ]; then
    echo "ERROR: PYR1 paired CSV MSA not found at ${PYR1_MSA}"
    echo ""
    echo "This should have been generated by the WT ternary prediction"
    echo "(predict_wt_ternary.sh with --use_msa_server)."
    exit 1
fi
echo "PYR1 paired MSA: ${PYR1_MSA} ($(wc -l < "${PYR1_MSA}") lines)"

if [ ! -f "${HAB1_MSA}" ]; then
    echo "ERROR: HAB1 paired CSV MSA not found at ${HAB1_MSA}"
    exit 1
fi
echo "HAB1 paired MSA: ${HAB1_MSA} ($(wc -l < "${HAB1_MSA}") lines)"

# ── Step 2: Check conjugate CSVs ────────────────────────────────────────
echo ""
echo "============================================"
echo "Step 2: Check conjugate CSVs"
echo "============================================"

LCA_CSV="${CONJUGATE_DIR}/boltz_lca_binary.csv"
GLCA_CSV="${CONJUGATE_DIR}/boltz_glca_binary.csv"
LCA3S_CSV="${CONJUGATE_DIR}/boltz_lca3s_binary.csv"

for csv_var in LCA_CSV GLCA_CSV LCA3S_CSV; do
    csv_path="${!csv_var}"
    if [ ! -f "${csv_path}" ]; then
        echo "ERROR: ${csv_var} not found at ${csv_path}"
        exit 1
    fi
    echo "${csv_var}: ${csv_path} ($(wc -l < "${csv_path}") lines)"
done

# ── Step 3: Generate ternary YAML inputs with paired MSAs ───────────────
echo ""
echo "============================================"
echo "Step 3: Generate ternary YAML inputs (paired MSAs)"
echo "============================================"

# Plain LCA
echo ""
echo "--- Plain LCA (ternary, paired) ---"
python "${PROJECT_ROOT}/scripts/prepare_boltz_yamls.py" \
    "${LCA_CSV}" \
    --out-dir "${LCA_YAML_DIR}" \
    --mode ternary \
    --msa "${PYR1_MSA}" \
    --hab1-msa "${HAB1_MSA}"

LCA_MANIFEST="${LCA_YAML_DIR}/manifest.txt"
LCA_TOTAL=$(wc -l < "${LCA_MANIFEST}")
LCA_ARRAY_MAX=$(( (LCA_TOTAL + BATCH_SIZE - 1) / BATCH_SIZE - 1 ))
echo "LCA ternary paired: ${LCA_TOTAL} YAMLs -> array=0-${LCA_ARRAY_MAX} (batch=${BATCH_SIZE})"

# GlycoLCA
echo ""
echo "--- GlycoLCA (ternary, paired) ---"
python "${PROJECT_ROOT}/scripts/prepare_boltz_yamls.py" \
    "${GLCA_CSV}" \
    --out-dir "${GLCA_YAML_DIR}" \
    --mode ternary \
    --msa "${PYR1_MSA}" \
    --hab1-msa "${HAB1_MSA}"

GLCA_MANIFEST="${GLCA_YAML_DIR}/manifest.txt"
GLCA_TOTAL=$(wc -l < "${GLCA_MANIFEST}")
GLCA_ARRAY_MAX=$(( (GLCA_TOTAL + BATCH_SIZE - 1) / BATCH_SIZE - 1 ))
echo "GLCA ternary paired: ${GLCA_TOTAL} YAMLs -> array=0-${GLCA_ARRAY_MAX} (batch=${BATCH_SIZE})"

# LCA-3-S
echo ""
echo "--- LCA-3-S (ternary, paired) ---"
python "${PROJECT_ROOT}/scripts/prepare_boltz_yamls.py" \
    "${LCA3S_CSV}" \
    --out-dir "${LCA3S_YAML_DIR}" \
    --mode ternary \
    --msa "${PYR1_MSA}" \
    --hab1-msa "${HAB1_MSA}"

LCA3S_MANIFEST="${LCA3S_YAML_DIR}/manifest.txt"
LCA3S_TOTAL=$(wc -l < "${LCA3S_MANIFEST}")
LCA3S_ARRAY_MAX=$(( (LCA3S_TOTAL + BATCH_SIZE - 1) / BATCH_SIZE - 1 ))
echo "LCA-3-S ternary paired: ${LCA3S_TOTAL} YAMLs -> array=0-${LCA3S_ARRAY_MAX} (batch=${BATCH_SIZE})"

# ── Step 4: Submit SLURM array jobs ──────────────────────────────────────
echo ""
echo "============================================"
echo "Step 4: Submit SLURM jobs"
echo "============================================"

SUBMIT_SCRIPT="${PROJECT_ROOT}/slurm/submit_boltz.sh"

echo "Submitting LCA ternary paired (${LCA_TOTAL} predictions)..."
LCA_JOB=$(sbatch --array=0-${LCA_ARRAY_MAX} \
    --job-name=boltz_lca_tp \
    "${SUBMIT_SCRIPT}" \
    "${LCA_MANIFEST}" "${LCA_OUTPUT_DIR}" "${BATCH_SIZE}" "${DIFFUSION_SAMPLES}" \
    | awk '{print $NF}')
echo "  LCA ternary paired job: ${LCA_JOB}"

echo "Submitting GLCA ternary paired (${GLCA_TOTAL} predictions)..."
GLCA_JOB=$(sbatch --array=0-${GLCA_ARRAY_MAX} \
    --job-name=boltz_glca_tp \
    "${SUBMIT_SCRIPT}" \
    "${GLCA_MANIFEST}" "${GLCA_OUTPUT_DIR}" "${BATCH_SIZE}" "${DIFFUSION_SAMPLES}" \
    | awk '{print $NF}')
echo "  GLCA ternary paired job: ${GLCA_JOB}"

echo "Submitting LCA-3-S ternary paired (${LCA3S_TOTAL} predictions)..."
LCA3S_JOB=$(sbatch --array=0-${LCA3S_ARRAY_MAX} \
    --job-name=boltz_lca3s_tp \
    "${SUBMIT_SCRIPT}" \
    "${LCA3S_MANIFEST}" "${LCA3S_OUTPUT_DIR}" "${BATCH_SIZE}" "${DIFFUSION_SAMPLES}" \
    | awk '{print $NF}')
echo "  LCA-3-S ternary paired job: ${LCA3S_JOB}"

# ── Summary ──────────────────────────────────────────────────────────────
echo ""
echo "============================================"
echo "ALL DONE — Ternary PAIRED predictions submitted"
echo "============================================"
echo ""
echo "Jobs submitted:"
echo "  LCA:       ${LCA_JOB} (array=0-${LCA_ARRAY_MAX}, ${LCA_TOTAL} predictions)"
echo "  GLCA:      ${GLCA_JOB} (array=0-${GLCA_ARRAY_MAX}, ${GLCA_TOTAL} predictions)"
echo "  LCA-3-S:   ${LCA3S_JOB} (array=0-${LCA3S_ARRAY_MAX}, ${LCA3S_TOTAL} predictions)"
echo ""
echo "Total: $(( LCA_TOTAL + GLCA_TOTAL + LCA3S_TOTAL )) ternary predictions (paired MSAs)"
echo "Diffusion samples: ${DIFFUSION_SAMPLES}"
echo ""
echo "Monitor: squeue -u \$USER"
echo ""
echo "After completion, aggregate results with:"
echo "  bash ${PROJECT_ROOT}/slurm/aggregate_boltz_lca_ternary.sh"
echo "  (update output dirs to *_paired in the aggregate script)"
