#!/bin/bash
#SBATCH --job-name=boltz_pred
#SBATCH --partition=atesting_a100
#SBATCH --account=ucb472_asc2
#SBATCH --qos=testing
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --mem=38400M
#SBATCH --time=01:00:00
#SBATCH --output=boltz_%A_%a.out
#SBATCH --error=boltz_%A_%a.err
# Usage:
#   sbatch --array=0-N submit_boltz.sh <manifest_file> <out_dir> [extra_boltz_flags]
#
# The manifest file is a text file with one YAML path per line,
# generated by prepare_boltz_yamls.py.
#
# Example:
#   python scripts/prepare_boltz_yamls.py variants.csv --out-dir boltz_inputs --template /path/to/3QN1.pdb --force-template --pocket-constraint
#   sbatch --array=0-$(( $(wc -l < boltz_inputs/manifest.txt) - 1 )) slurm/submit_boltz.sh boltz_inputs/manifest.txt boltz_output

cd "$SLURM_SUBMIT_DIR"

module load anaconda cuda/12.1.1
source activate boltz_env

MANIFEST="$1"
OUT_DIR="${2:-boltz_output}"
EXTRA_FLAGS="${@:3}"

if [ -z "$MANIFEST" ]; then
    echo "ERROR: Must provide manifest file as first argument"
    exit 1
fi

# Get the YAML file for this array task
YAML_PATH=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" "$MANIFEST")

if [ -z "$YAML_PATH" ]; then
    echo "ERROR: No entry at index $SLURM_ARRAY_TASK_ID in $MANIFEST"
    exit 1
fi

echo "Task $SLURM_ARRAY_TASK_ID: predicting $YAML_PATH"

boltz predict "$YAML_PATH" \
    --out_dir "$OUT_DIR" \
    --cache /projects/ryde3462/software/boltz_cache \
    --recycling_steps 3 \
    --diffusion_samples 5 \
    --output_format pdb \
    $EXTRA_FLAGS

EXIT_CODE=$?
echo "Exit code: $EXIT_CODE"
echo "Done: $(basename "$YAML_PATH")"
exit $EXIT_CODE
